server.port=8080
spring.jackson.date-format=yyyy-MM-dd
spring.jackson.time-zone=Europe/Moscow
logging.level.org.zalando.logbook=TRACE

# Database configuration
spring.datasource.url=jdbc:h2:file:./db/filmorate;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# SQL initialization
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql